def main():
    import turtle
    t = turtle.Turtle()
    t.pensize(5)
    t.pencolor("Blue")
    t.shape("turtle")
    side_length = 89;
    t.left(side_length)
    t.forward(90)
    t.right(side_length)
    t.forward(90)
    t.backward(side_length)
    t.right(90)
    t.forward(90)
    t.left(side_length)
    t.forward(90)
    t.penup()
    t.forward(90)
    t.pendown()
    t.left(90)
    t.forward(side_length)
    t.left(180)
    t.forward(40)
    t.left(90)
    t.forward(side_length)
    t.left(90)
    t.forward(side_length)
    t.left(180)
    t.forward(side_length)
    t.left(360)
    t.forward(side_length)
main()
